// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alfunc
double alfunc(NumericVector BVEC, NumericMatrix X, NumericVector Y, NumericMatrix M, NumericVector MU, double LAMBDA, double CONST1, double CONST2, int U, int V);
RcppExport SEXP _biplotEZ_alfunc(SEXP BVECSEXP, SEXP XSEXP, SEXP YSEXP, SEXP MSEXP, SEXP MUSEXP, SEXP LAMBDASEXP, SEXP CONST1SEXP, SEXP CONST2SEXP, SEXP USEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type BVEC(BVECSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< double >::type LAMBDA(LAMBDASEXP);
    Rcpp::traits::input_parameter< double >::type CONST1(CONST1SEXP);
    Rcpp::traits::input_parameter< double >::type CONST2(CONST2SEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(alfunc(BVEC, X, Y, M, MU, LAMBDA, CONST1, CONST2, U, V));
    return rcpp_result_gen;
END_RCPP
}
// optimize_spline
List optimize_spline(NumericVector BVEC, NumericMatrix X, NumericVector Y, NumericMatrix M, NumericVector MU, double LAMBDA, double CONST1, double CONST2, int U, int V, double TAU, double FTOL, double TINY, int ITMAX);
RcppExport SEXP _biplotEZ_optimize_spline(SEXP BVECSEXP, SEXP XSEXP, SEXP YSEXP, SEXP MSEXP, SEXP MUSEXP, SEXP LAMBDASEXP, SEXP CONST1SEXP, SEXP CONST2SEXP, SEXP USEXP, SEXP VSEXP, SEXP TAUSEXP, SEXP FTOLSEXP, SEXP TINYSEXP, SEXP ITMAXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type BVEC(BVECSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< double >::type LAMBDA(LAMBDASEXP);
    Rcpp::traits::input_parameter< double >::type CONST1(CONST1SEXP);
    Rcpp::traits::input_parameter< double >::type CONST2(CONST2SEXP);
    Rcpp::traits::input_parameter< int >::type U(USEXP);
    Rcpp::traits::input_parameter< int >::type V(VSEXP);
    Rcpp::traits::input_parameter< double >::type TAU(TAUSEXP);
    Rcpp::traits::input_parameter< double >::type FTOL(FTOLSEXP);
    Rcpp::traits::input_parameter< double >::type TINY(TINYSEXP);
    Rcpp::traits::input_parameter< int >::type ITMAX(ITMAXSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_spline(BVEC, X, Y, M, MU, LAMBDA, CONST1, CONST2, U, V, TAU, FTOL, TINY, ITMAX));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_biplotEZ_alfunc", (DL_FUNC) &_biplotEZ_alfunc, 10},
    {"_biplotEZ_optimize_spline", (DL_FUNC) &_biplotEZ_optimize_spline, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_biplotEZ(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
